- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - horizon-openstack-tox-python3-django111
